/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Product {
  'tradeOffs' : Array<string>,
  'name' : string,
  'description' : string,
  'productId' : string,
  'returnReasons' : Array<string>,
  'sellerId' : string,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface Review {
  'verified' : boolean,
  'content' : string,
  'userId' : string,
  'usageDays' : bigint,
  'productId' : string,
  'rating' : bigint,
  'reviewId' : string,
}
export interface Seller {
  'totalOrders' : bigint,
  'policyViolations' : bigint,
  'name' : string,
  'trustScore' : bigint,
  'historyTimeline' : Array<string>,
  'accountAgeDays' : bigint,
  'sellerId' : string,
  'disputesWon' : bigint,
  'disputesLost' : bigint,
  'penalties' : bigint,
}
export interface UserProfile {
  'name' : string,
  'purchaseHistory' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'addSeller' : ActorMethod<[Seller], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllSellers' : ActorMethod<[], Array<Seller>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProductReviews' : ActorMethod<[string], Array<Review>>,
  'getSeller' : ActorMethod<[string], [] | [Seller]>,
  'getSellerProducts' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];